apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-lc-helloworld
    capacity: 15
    expires: 300m
    orphaned: 15m
