apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    ingress:
      domain: workshop.captainvirtualization.in
#     secret: secret-workshop
    registration:
      type: one-step
      enabled: true
    credentials:
      admin:
        username: admin
        password: Welcome11!
  workshops:
  - name: lab-lc-helloworld
    capacity: 25
    expires: 300m
    orphaned: 45m
  - name: To-workshop
    capacity: 10
    expires: 30m
    orphaned: 5m
