apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: one-step
      enabled: false
    credentials:
      Admin:
        Password:  Newstart@1
        Username:  Admin
      Robot:
        Password:  Welcome11!
        Username:  srini 
  workshops:
  - name: lab-lc-helloworld
    capacity: 10
    expires: 120m
    orphaned: 5m
