apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: eknathdemotkg
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-lc-helloworld
    capacity: 100
    expires: 60m
    orphaned: 5m
