apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: one-step
      enabled: true
  workshops:
  - name: lab-lc-helloworld
    capacity: 10
    expires: 120m
    orphaned: 5m
