apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: one-step
      enabled: true
    credentials:
      admin:
        username: admin
        password: Welcome11!
    tls:
      - hosts:
        - *.workshop.captainvirtualization.in
        secretName: secret-workshop
  workshops:
  - name: lab-lc-helloworld
    capacity: 25
    expires: 300m
    orphaned: 45m
