apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: one-step
      enabled: false
    credentials:
      admin:
        username: admin
        password: Welcome11!
      robot:
        username: robot-user
        password: Newstart@1
  workshops:
  - name: lab-lc-helloworld
    capacity: 25
    expires: 300m
    orphaned: 45m
