apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: one-step
      enabled: false
    #@ if data.values.eduk8s:
    credentials:
      admin:
        username: admin
        password: #@ data.values.eduk8s.adminPassword
      robot:
        username: robot-user
        password: #@ data.values.eduk8s.robotPassword
    #@ end
  workshops:
  - name: lab-lc-helloworld
    capacity: 10
    expires: 120m
    orphaned: 5m
