apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: one-step
      enabled: true
    credentials:
      admin:
        username: admin
        password: "Newstart@1"
      robot:
        username: robot-user
        password: "Welcome11!"
  workshops:
  - name: lab-lc-helloworld
    capacity: 10
    expires: 120m
    orphaned: 5m
