apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: partnerse
spec:
  portal:
    registration:
      type: one-step
      enabled: true
    credentials:
      admin:
        username: admin
        password: Welcome11!
      user1:
        username: parterse-user1
        password: Newstart@1
      user2:
        username: parterse-user2
        password: Newstart@2
      user3:
        username: parterse-user3
        password: Newstart@3
  workshops:
  - name: lab-lc-helloworld
    capacity: 25
    expires: 300m
    orphaned: 45m
