apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-lc-helloworld
spec:
  title: Hello! from Eknath
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/Eknathreddy09/lab-lc-helloworld
  content:
    image: quay.io/eduk8s/lab-workshop-builder:master
    files: github.com/Eknathreddy09/lab-lc-helloworld:lc-test
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
