apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-hello-world-sample
spec:
  title: Hello World Sample
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/chdubois/lab-hello-world
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/chdubois/lab-hello-world.git
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
